
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# filterwheel.py - Alpaca API responders for Filterwheel
#
# Author:   Your R. Name <your@email.org> (abc)
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
# ??-???-????   abc Initial edit

from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes

logger: Logger = None

from filterwheel_device import FilterWheel
# from filterwheel_simulated import FilterWheel

fw = FilterWheel()

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
## EDIT FOR YOUR DEVICE ##
class FilterwheelMetadata:
    """ Metadata describing the Filterwheel Device. Edit for your device"""
    Name = 'Thibault Filterwheel' # TODO modifié ici
    Version = '##DRIVER VERSION AS STRING##'
    Description = 'Thibault ASCOM Filterwheel' # TODO modifié ici
    DeviceType = 'Filterwheel'
    DeviceID = '##GENERATE A NEW GUID AND PASTE HERE##' # https://guidgenerator.com/online-guid-generator.aspx
    Info = 'Alpaca Sample Device\nImplements IFilterwheel\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = 0.0 ##YOUR DEVICE INTERFACE VERSION##        # IFilterwheelVxxx # TODO modifié ici


# --------------------
# RESOURCE CONTROLLERS
# --------------------

@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------
            ### CONNECT THE DEVICE ### TODO ajouté ici
            # ------------------------
            fw.connect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Filterwheel.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # -------------------------------------
            ### READ CONN STATE ### TODO ajouté ici
            # -------------------------------------
            is_conn = fw.isConnected()
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Filterwheel.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            # --------------------------------------
            ### CONNECT OR DISCONNECT THE DEVICE ### TODO ajouté ici
            # --------------------------------------
            # Booléen envoyé par le client

            if conn:
                fw.connect()
            else:
                fw.disconnect()
                
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req, # Put is actually like a method :-(
                            DriverException(0x500, 'Filterwheel.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------------
            ## GET CONNECTING STATE ## TODO modifié ici
            # ------------------------------
            val = fw.isConnecting()
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Filterwheel.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FilterwheelMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class devicestate:
    # The devicestate class exposes internal diagnostic or operational information
    # about the filter wheel (e.g. position, moving state, errors) as a list of key/value pairs.
    # It allows client software to monitor the device’s current status beyond standard properties.
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected() : ##IS DEV CONNECTED##: # TODO modifié ici
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        try:
            # ----------------------
            val = []
            # val.append(StateValue('## NAME ##', ## GET VAL ##))
            # TODO modifié ici
            val.append(StateValue('Position', fw.currentPosition))
            val.append(StateValue('Angle', fw.currentAngle))
            val.append(StateValue('Moving', fw.isMoving()))
            val.append(StateValue('Error', fw.lastError))
            # ----------------------
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'filterwheel.Devicestate failed', ex)).json


class disconnect:
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ---------------------------
            ### DISCONNECT THE DEVICE ### #TODO ajouté ici
            # ---------------------------
            fw.disconnect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Filterwheel.Disconnect failed', ex)).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FilterwheelMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FilterwheelMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class driverversion():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FilterwheelMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class name():
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FilterwheelMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    # TODO : permettra plus tard d'ajouter des actions personalisées
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse([], req).json  # Not PropertyNotImplemented

@before(PreProcessRequest(maxdev))
class focusoffsets:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected() : ##IS DEV CONNECTED##: #TODO modifié ici
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ## # TODO modifié ici 
            # ----------------------
            val = fw.get_focus_offsets()
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Filterwheel.Focusoffsets failed', ex)).json
            
    # TODO pourra être ajouté on_put pour modifier les offsets

@before(PreProcessRequest(maxdev))
class names:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected() :##IS DEV CONNECTED##: # TODO modifié ici
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ## # TODO modifié ici
            # ----------------------
            val = fw.get_names()
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Filterwheel.Names failed', ex)).json
            
    # TODO pourra être ajouté on_put pour modifier les names
    
@before(PreProcessRequest(maxdev))
class NumberOfPositions:
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected():
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = len(fw.filter_names)  # nombre de filtres
            resp.text = PropertyResponse(int(val), req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Filterwheel.MaxStep failed', ex)).json

@before(PreProcessRequest(maxdev))
class position:

    def on_get(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected() : ##IS DEV CONNECTED##: #TODO modifié ici
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        try:
            # ----------------------
            ## GET PROPERTY ## #TODO modifié ici
            # ----------------------
            val = fw.get_position()
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Filterwheel.Position failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not fw.isConnected() : ## IS DEV CONNECTED ##:#TODO modifié ici
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        
        positionstr = get_request_field('Position', req)      # Raises 400 bad request if missing
        try:
            position = int(positionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Position {positionstr} not a valid integer.')).json
            return
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details! # TODO ajouté ici
        if position < 0 or position >= len(fw.filter_names):
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Position {position} out of range.')).json
            return
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            fw.set_position(position) 
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Filterwheel.Position failed', ex)).json

